create table vehicles (
    id int generated by default as identity primary key,
    make varchar(256),
    model varchar(256),
    model_year int,
    price numeric(9,2),
    seller_id int references sellers(id)
);
